### PR TITLE
Plugin system

### PR DESCRIPTION
**Pull request by simov**
Closes #1400 
Closes #1406 

I just merged https://github.com/request/request/pull/1400 and https://github.com/request/request/pull/1406 here + refactored all of the 4 plugins to use similar structure.

### CODE REVIEW

**Comment by nylen** [comment]
I like the concept.  I'm a little worried about unexpectedly breaking things though, like #1407.

I have been swamped lately (just accepted a job with Automattic!) so I'll need at least a few days to do a proper review.  @mikeal @FredKSchott @seanstrom etc. any help appreciated.

**Comment by simov** [comment]
I'm really not changing that much at this stage, just moving code around, the instance bug with auth is very silly, but apparently not caught by any of the tests.

**Comment by nylen** [comment]
I agree, I feel like I could have caught that in reviewing though, so I'd like to be more thorough this time.

**Comment by simov** [comment]
OK, my point in https://github.com/request/request/issues/1409 was that it's about code modified in this PR + I already merged two other PR's here, so I don't want to push even more things here :)

**Comment by mikeal** [comment]
I don't have time to do a full review but I will say that I like this approach. I'll be impressed if you can actually work the forwarding logic in to a plugin, that logic always seemed to infect parts of the code I never thought I'd have to worry about :)

**Comment by simov** [comment]
@mikeal I'm not familiar with the entire code base in details tbh, but still the refactoring should start from somewhere.

**Comment by lalitkapoor** [comment]
@nylen off topic, but congrats on the new job!! :)

**Comment by seanstrom** [comment]
I'll be doing a thorough review today :)

**Comment by simov** [comment]
Thanks @seanstrom take a look at this PR https://github.com/request/request/pull/1406 too, as most of my latest ideas are there. Also not really that much changed at this point, I'm really just moving code into separate scopes as I see fit. For example the last one - the redirect one is just something that I thought it deserves it's own scope, and in fact except two of the fields in this newly created class are used externally, so it looks like a separate entity after all.

**Pull request closed without merging**
