### PR TITLE
close timeoutTimer when abort request

### PR DESCRIPTION
**Pull request by ranbochen**
request.abort must close timeout timer.
if not close it, listener will receive a timeout error.

### CODE REVIEW

**Comment by FredKSchott** [comment]
@ranbochen can you fix the lint error? See: http://eslint.org/docs/rules/handle-callback-err.html

From the docs, you could just add: `if (err) {}` to that callback to show that you're intentionally not handling the error.

**Comment by ranbochen** [comment]
if (err) {} 
trigger
no-empty rule
!!!

**Comment by qubyte** [comment]
What's the status of this PR?

**Comment by Mudrekh** [comment]
I would also like to know the status of the PR. 

Ran into this on a server in which I need to close requests when users are no longer interested, even if they haven't finished or eventually timeout. My problem is this timeout error is propagated all the way up and causes the application to crash since I try to clean up the request and all listeners when I no longer care about the result. 

It might be moot, but here is a simplified example of what I'm doing.

```javascript
var request = require("request");

var opts = {
  url: "http://192.168.1.255",
  timeout: 2000
};

var r = request.get(opts);
setTimeout(function() {
  console.log("Aborting request!");
  r.abort();
  // clearTimeout(r.timeoutTimer);
}, 100);

process.stdin.on("data", function() {
  process.exit();
});
```

Ideally this program should run until the user enters something, but the timeout causes it to crash. Its worth noting that the program doesn't crash if you don't abort within a timeout, have a callback defined, or attach an error listener that isn't cleared. Also, if you manually clear the timeoutTimer  (like in the PR!), the programs continues to run.

**Comment by FredKSchott** [comment]
This PR has been closed as "abandoned" as a part of an automated cleanup. If this is a mistake and you are still interested in merging this PR, please do the following:

1. [ ] Rebase your changes onto the `master` branch (even if there are no merge conflicts, we want to make sure your change is under the most recent tests).
2. [ ] Push your updated branch to Github to update this PR.
3. [ ] Make sure this PR's Travis tests are still passing. (Run `npm test` locally if tests are still failing).
4. [ ] Comment here to let us know that you've updated the PR and are still interested in getting it merged. Somebody from the project will respond and work with you to review.

Thank you for your understanding. If you have any questions, please check out https://github.com/request/request/issues/2556 and feel free to comment / ask anything there.

**Pull request closed without merging**
