### PR TITLE
Add node.js 0.12 and io.js to travis.yml

### PR DESCRIPTION
**Pull request by demohi**

### CODE REVIEW

**Comment by simov** [comment]
Apparently it won't be as straightforward as this.

**Comment by FredKSchott** [comment]
A lot of request logic was changed during the last two years in v0.11, I'm not suprised :/

**Comment by nicolasmccurdy** [comment]
Node 0.12 and io.js support seems like it's both important to this project and at high demand. I think it would benefit this project to merge this pull request into a branch that would then be used for 0.12 and io.js development (so everyone can test against 0.12 and io.js in CI without breaking master's build).

**Comment by nicolasmccurdy** [comment]
By the way, does anyone know if it's possible to allow failures for specific Node versions on Travis? It has something like that for environment variables, but if we can figure out a way to get this to work for Node versions we can show 0.12 and io.js results in CI but prevent the build from being marked as failing while the fixes are in development

**Comment by nicolasmccurdy** [comment]
To answer my own question, yes, it is possible to allow failures on specific versions of Node. I have created a pull request similar to yours, but with allowed failures: #1453.

**Pull request merged**
