### PR TITLE
Add a test for the forever agent

### PR DESCRIPTION
**Pull request by akshayp**
@nicolasmccurdy Adding a test for https://github.com/request/request/issues/1472. This passes on node 0.10 and fails on 0.12.x and iojs

Closes https://github.com/request/request/issues/1472

### CODE REVIEW

**Comment by nicolasmccurdy** [comment]
:+1:

**Comment by FredKSchott** [comment]
+1 This should probably be merged, even if it is breaking. Any objections @nylen @seanstrom @simov ?

**Comment by seanstrom** [comment]
I agree we should take this, but we need to patch asap.
Im willing to take a look at this tonight/tomorrow.

**Comment by simov** [comment]
@seanstrom that would be great. Although having this PR and the failing test is good, I don't think merging it without a fix is the right thing to do, as it may stay that way indefinitely.

**Comment by seanstrom** [comment]
Okay good news, I got the tests to pass by patching ForeverAgent.
I'll have a PR for that up really soon.

**Comment by seanstrom** [comment]
Here's the PR for the patch, https://github.com/request/forever-agent/pull/25

**Comment by simov** [comment]
@akshayp can you bump the `forever-agent` version to `0.6.0` and push so that we can see the tests passing.

**Comment by akshayp** [comment]
@simov Pushed and tests are now all passing. Thanks for the patch @seanstrom!

**Pull request merged**
