### PR TITLE
Allow :// to occur in the path even when baseUrl is used, as long as it's not at the beginning.

### PR DESCRIPTION
**Pull request by johnnysprinkles**
Fixes https://github.com/request/request/issues/2857

## PR Checklist:
- [x] I have run `npm test` locally and all tests are passing.
- [x] I have added/updated tests for any new behavior.
       
- [x] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]
       

## PR Description
This is a one line fix, it just tightens down the check on "path doesn't look like it starts with a scheme" logic to be more precise and not bleed over to valid paths.

### CODE REVIEW

**Comment by johnnysprinkles** [comment]
Not sure why these checks fail... I did run `npm run lint` and `npm test` locally, which succeed.

**Comment by johnnysprinkles** [comment]
Anybody there to look at this pull request?

**Comment by johnnysprinkles** [comment]
Hello?

**Comment by robertvanhoesel** [comment]
Seconding for someone to accept PR, this is a legit fix.

**Comment by johnnysprinkles** [comment]
I don't know how to figure out who owns a Github repo -- I can see the "contributors" but not sure about owners.

**Comment by robertvanhoesel** [comment]
Looking at the commits this year, @mikeal or @reconbot seem to have merged some PRs. However as pointed out in #2978 they are both quite busy. 

The problem with checks is probably a config or dependency issue. Recent PRs have different checks and are passing, so rebasing on top of the base branch for a new check might help.

**Comment by johnnysprinkles** [comment]
Ping

**Pull request closed without merging**
