### PR TITLE
Test for forever-agent PR #29 - Enable socket reuse

### PR DESCRIPTION
**Pull request by mgorczyca**
Added as requested by @simov

### CODE REVIEW

**Comment by mgorczyca** [comment]
Looks like the error is that the test failed. The forever-agent PR #29 is needed for the test to succeed.

**Comment by simov** [comment]
@mgorczyca thanks for your input. However your test is failing only on 0.10, and it is passing with 0.12 and io.js without applying your fix from the forever-agent repo. The error you are seeing in TravisCI is that the next test is timing out, which is completely different issue. Just skip the next test `tape.skip` and run `tape tests/test-agent.js` with both 0.12 and iojs - you'll see that your test is passing, so I'm not sure what exactly it tests.

**Comment by mgorczyca** [comment]
Thanks for your feedback @simov. I thought I had run my test in a pure 0.12 environment, and discovered one override to 0.10. I originally discovered the problem in 0.10 where the test still (properly) fails. Once I corrected my 0.12 environment, the test passes there for me, just as it does for you. We are planning to use 0.12 at this point, so we can close the issue and the PR if you agree that is best.

**Comment by simov** [comment]
Closing in favor of https://github.com/request/request/pull/1671 - request now defaults to `http(s).Agent` in node 0.12+ when the `forever` option is used.

**Pull request closed without merging**
