### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by arbaaz**
uri is not defined.

### CODE REVIEW

**Comment by simov** [comment]
Hi, @arbaaz. I honestly don't see what is this PR fixing. Feel free to elaborate.

**Comment by arbaaz** [comment]
When I used the same snippet in my code exception occurred('uri is not defined'). When I changed to `url` it started working.

**Comment by simov** [comment]
Now I see it:

```js
var url = 'http://www.google.com';
```

is defined in the code block from above. Is that it?

**Comment by arbaaz** [comment]
Yes. that is it.

**Pull request merged**
