### PR TITLE
Update README to simplify & update convenience methods

### PR DESCRIPTION
**Pull request by FredKSchott**
## PR Checklist:
- [X] I have run `npm test` locally and all tests are passing.
- [X] I have added/updated tests for any new behavior.
       
- [X] If this is a significant change, an issue has already been created where the problem / solution was discussed: N/A
       

## PR Description

I realized that there is a README section on the request convenience methods after merging #2541, so I made a quick update to that section to simplify it (no need for it to be so long) and update it (add the newest `request.options()` method).

/cc @jamesseanwright

### CODE REVIEW

**Comment by jamesseanwright** [comment]
Oops, sorry I missed this! Thanks for the update.

**Comment by tsuzfr** [comment]
Thanks for merging the update. However, v2.81.1 does not seem to be in the npm directory. The latest one is v2.81.0. Do you think we can update this?

**Comment by FredKSchott** [comment]
That's intentional to differentiate between the version on npm & the version on github/master

**Comment by nylen** [comment]
The only times the .0 vs .1 thing has ever come up, it has been more confusing than helpful.

**Pull request merged**
