### PR TITLE
dependency(har-validator): update to ~v4.2.0

### PR DESCRIPTION
**Pull request by ahmadnassri**
- `v3.x` introduces massive performance improvement.
- `v4.x` minimizes dependencies.

### CODE REVIEW

**Comment by simov** [comment]
Probably version 4.x will be even better regarding the dependencies count :) I'm glad you removed the CLI related modules from the core har module.

**Comment by ahmadnassri** [comment]
indeed. as soon as I made this PR, I quickly followed with more cleanup! I shall update it now to 4.x

**Comment by ahmadnassri** [comment]
PR updated.

**Comment by ahmadnassri** [comment]
struggled getting the local setup to test needed browser fixes for the test here to succeed, seems to be only triggering on Travis ... but finally got it.

**Pull request merged**
