### PR TITLE
req.body undefined or null same logic branch

### PR DESCRIPTION
**Pull request by stonephp**
I found the problem when use frisby.

### CODE REVIEW

**Comment by simov** [comment]
This breaks our tests because `null` is allowed value for JSON encoded request body. Can you elaborate on what exactly your use case is?

**Comment by stonephp** [comment]
I trace the code, found ./request.js 1212 line, self._qs.rfc3986(self.body).
```js
Querystring.prototype.rfc3986 = function (str) {
   return str.replace(/[!'()*]/g, function (c) {
```

Here, str.replace throw error, when str is null.

**Comment by simov** [comment]
Yep, I know that it throws there. Can you provide a short code example of your options setup that you are passing to request?

**Comment by stonephp** [comment]
```js
request = require('request');

request({
  json: true,
  uri: 'http://www.google.com/',
  body: null,
  method: 'GET',
  headers: {
    'content-type': 'application/x-www-form-urlencoded'
  }
});
```

**Comment by simov** [comment]
Oh, the `body:null` thing .. got it! You have to remove the semicolons `;` in your last commit - TravisCI is failing again.

**Comment by fritx** [comment]
image

Same here..  request@2.79.0

**Pull request closed without merging**
