### PR TITLE
Parameters encoded to base 64 should be decoded as UTF-8, not ASCII.

### PR DESCRIPTION
**Pull request by albanm**
This fixes a bug that I have currently. Some users were created with special characters in password but could not authenticate through request.auth method afterward.

### CODE REVIEW

**Comment by froatsnook** [comment]
Is UTF-8 the right encoding to use, though?  Or should it be ISO-8859-1?  Apparently there's no consistency among the spec, browser implementations, and server implementations: https://code.google.com/p/chromium/issues/detail?id=25790

I would say we should use utf-8 as you suggested, but also accept a `Buffer` for `user` and/or `pass` for users dealing with servers that expect ISO-8859-1 instead of utf-8.

**Comment by simov** [comment]
Thanks @albanm ! Also the remarks about ISO-8859-1 are correct, but I think we should be good with just `utf8` for now :+1:

**Comment by albanm** [comment]
Thanks !

Is it possible to release a small patch version containing this fix ?

**Comment by simov** [comment]
The next request release is scheduled for the upcoming week, I can't tell you exact day and time, but we're rounding up the last features/bugfixes and then we're good to go.

**Pull request merged**
