### PR TITLE
Update hawk to 7.0.7

### PR DESCRIPTION
**Pull request by kornel-kedzierski**
## PR Checklist:
- [ ] I have run `npm test` locally and all tests are passing.
- [x] I have added/updated tests for any new behavior.
       
- [ ] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]

### CODE REVIEW

**Comment by mickhansen** [comment]
This was a breaking change in my case, the new version of hawk has a node engine of >= 8 and it's sntp dependency has `async` in the codebase.

We run code with request on lambda which doesn't go higher than 6.10 and we don't normally compile dependencies with babel (not sure if this is expected).

**Comment by Apollon77** [comment]
same problem here. Please revert that ASAP!!

**Comment by ezraroi** [comment]
+1

**Comment by justinkjchang** [comment]
+1

**Comment by AlCalzone** [comment]
> the new version of hawk has a node engine of >= 8 and it's sntp dependency has async in the codebase.

Well... this is bad.

**Comment by cschuff** [comment]
+1

**Comment by timocov** [comment]
+1

**Comment by Apollon77** [comment]
@simov

**Comment by alanquigley** [comment]
+1

**Comment by vladimir-tikhonov** [comment]
That's why you shouldn't ignore CI builds - https://travis-ci.org/request/request/jobs/345197366 :)

**Comment by ByronLian** [comment]
+1

**Comment by yutackall** [comment]
+1

**Comment by Apollon77** [comment]
Interestingly travis-ci is still "red"

**Comment by Karthi-R** [comment]
Finally found this! thanks for the quick fix.

**Comment by simov** [comment]
More information about why this PR was reverted here: https://github.com/request/request/issues/2891#issuecomment-372271727

**Pull request merged**
