### PR TITLE
Reorders README to be more useful to beginners

### PR DESCRIPTION
**Pull request by rockbot**
Puts the API at the top, with details for how to do more complex things later on.

### CODE REVIEW

**Comment by simov** [comment]
I like it, the most often questions in the chat recently are related to simple options usage.

**Comment by nylen** [comment]
I know our docs could be better organized, but I don't think this is the right way to go.  Our first heading is "Super simple to use", then having all of our 3897 options right underneath that kinda makes me laugh.

How about a link in the first section instead, something like:

> If you need something different then there's probably [an option to customize it](#options).

**Comment by simov** [comment]
Or like big fat 

### [Options](https://github.com/request/request#requestoptions-callback)

link, but you can miss that as well.

Anyway without a fixed sidebar navigation, containing each and every header tag in it, finding info will be only possible through searching using the browser's search.

**Comment by FredKSchott** [comment]
Agreed, "Super simple to use" followed immediately by 100s of options seems glaringly contradictory.

Maybe rename the header for the section on options to address "super simple to use... but super powerful/flexible as well"

**Comment by simov** [comment]
I think _super simple to use_ refers to the API at a whole, not to the options count (although there are some option combinations that are a bit tricky)

**Comment by nylen** [comment]
I still don't like the idea of putting all of our options at the top.  I think it's overwhelming to beginners rather than friendly, and I like the streaming section being next because when I go to the docs usually I am answering the question "ok, how do I do streaming again?"

I think it's time to put some more effort into restructuring our documentation, including splitting it into multiple files because it has gotten really long.  I'm creating a separate issue with some proposed restructuring notes.

**Pull request closed without merging**
