### PR TITLE
Add store accessor to the RequestJar.

### PR DESCRIPTION
**Pull request by axfree**
With this patch, you can remove or find cookies from the store like this.

``` javascript
var FileCookieStore = require('tough-cookie-filestore');
var jar = request.jar(new FileCookieStore(__dirname + '/data/cookies.json'));

jar.store.removeCookie('foo.com', '/', 'foo', function (err) {
    ...
});

jar.store.removeCookies('example.com', null, function (err) {
    ...
});

jar.store.findCookies('example.com', null, function (err, cookies) {
    ...
});

```

### CODE REVIEW

**Comment by simov** [comment]
Looking good to me, @lalitkapoor any thoughts on this?

**Comment by lalitkapoor** [comment]
:+1:

**Comment by simov** [comment]
Great! But we need a test @axfree.

**Comment by mike442144** [comment]
@simov I have same problem now, Can you modify your api in `cookies.js`, just use `jar` like a normal `CookieJar` instance in `tough-cookie`. Or any progress with this issue?

**Comment by FredKSchott** [comment]
This PR has been closed as "abandoned" as a part of an automated cleanup. If this is a mistake and you are still interested in merging this PR, please do the following:

1. [ ] Rebase your changes onto the `master` branch (even if there are no merge conflicts, we want to make sure your change is under the most recent tests).
2. [ ] Push your updated branch to Github to update this PR.
3. [ ] Make sure this PR's Travis tests are still passing. (Run `npm test` locally if tests are still failing).
4. [ ] Comment here to let us know that you've updated the PR and are still interested in getting it merged. Somebody from the project will respond and work with you to review.

Thank you for your understanding. If you have any questions, please check out https://github.com/request/request/issues/2556 and feel free to comment / ask anything there.

**Pull request closed without merging**
