### PR TITLE
Always set request timeout on keep-alive connections

### PR DESCRIPTION
**Pull request by mscdex**

### CODE REVIEW

**Comment by mscdex** [comment]
The changes in 001eae3d479a13350b06b8d3f8182b2060a2c60d would cause the http request timeout to only get set if a new socket was being used. This PR makes sure it gets set even when we're already connected.

**Comment by simov** [comment]
I can publish another patch no problem, I had to ask you first. So is this good for merging/publishing?

**Comment by mscdex** [comment]
It should be good to go now, I've added a test for it.

**Comment by simov** [comment]
Thank you! Published.

**Pull request merged**
