### PR TITLE
Fixing tests to pass on io.js

### PR DESCRIPTION
**Pull request by mikeal**
This fixes all the tests but test-https, which is so convoluted I'm having a hard time figuring out what is broken.

### CODE REVIEW

**Comment by FredKSchott** [comment]
:+1:  but tests are now failing on node as well

**Comment by simov** [comment]
I think we should merge at least the passing test fixes into master

cc @nicolasmccurdy the only failing test on node 0.12/iojs is the strict branch in test-https.js

**Comment by simov** [comment]
It's not fixed, I just merged master so that the work can continue here (the certificates were expired) Once the failing test is fixed we should fix the readme and the travis.yml

**Comment by nicolasmccurdy** [comment]
Can we add Node 0.12 and io.js to the Travis config (see #1415) so we can see the results of these fixes in CI ?

**Comment by nicolasmccurdy** [comment]
> I think we should merge at least the passing test fixes into master

@simov Agreed.

**Comment by simov** [comment]
Ok, I'm going to merge the passing test from this branch, then it's probably a good idea to have a separate issue only for the failing https test, and put a bounty on it @nylen @mikeal ?

**Comment by simov** [comment]
Merged. Check your PRs from small merge conflicts (if any)

**Pull request merged**
