### PR TITLE
Paraquire

### PR DESCRIPTION
**Pull request by nickkolok**
## PR Checklist:
- [x] I have run `npm test` locally and all tests are passing.
- [x] I have added/updated tests for any new behavior.
       
The new behavior does not contain API changes or improvements, it is only about security, so **no new tests needed**
- [x] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A]
       

## PR Description

NPM ecosystem is [quite unresistant](https://github.com/ChALkeR/notes/blob/master/Gathering-weak-npm-credentials.md) against dependency attacks. It means that if a hacker gets control over one small abandoned package, the hacker gets control over all it's dependents, dependents of dependents, etc.
`request` is a very popular dependency and, on the other side, has some dependencies. So, hijacking only one of `request`'s dependencies will be very crucial for whole NPM ecosystem. This PR improves `request` security by jailing most dependencies into `paraquire` - secure [alternative](https://github.com/nickkolok/paraquire) for standard `require`. I did my best, however, I couldn't manage to define the rights needed by some libraries, so that sides remain unprotected.

I realise that this PR probably will not be merged, but I hope for having a productive discussion. I could not open an issue first, because only PR can show my suggestion clearly enough.

### CODE REVIEW

**Comment by nickkolok** [comment]
UPD: currently `paraquire` is incompatible with `browserify`. Do you really need such compatibility?

**Comment by mikeal** [comment]
> UPD: currently paraquire is incompatible with browserify. Do you really need such compatibility?

Yes :)

**Comment by nickkolok** [comment]
Thanks for such a fast reply!

**Comment by nickkolok** [comment]
So, are you interested in such a security improvement? Maybe your have another projects where such compatibility is not necessary? Maybe you can advice me somebody who is interested in such security issues?
Finally, if `browserify` compatibility will be reached (possibly by plug-in for `browserify`) - should I continue my work on this pull request?

**Pull request closed without merging**
