### PR TITLE
Urlparse exception

### PR DESCRIPTION
**Pull request by rifflock**
This is the same as #1873 but with travis.ci fixes.

Fixes #1873

### CODE REVIEW

**Comment by simov** [comment]
That's great, but we need a test for it :)

**Comment by rifflock** [comment]
Okay, I'll see if I can get something reproducible put together. I'm pretty sure the issue occurs when the decode function gets half of a utf8 surrogate pair, so... I'll take a crack at it.

**Comment by simov** [comment]
Yep, basically the description is here https://github.com/request/request/issues/1864 the test should be put in test-redirect.js I guess.

**Comment by rifflock** [comment]
Welp, I'm at a bit of a loss.
I decided to use the "Pile of Poo" test from 
https://mathiasbynens.be/notes/javascript-unicode
And while I can reproduce the exception if I try to use `decodeURIComponent` on one of the surrogate pairs from the pile of poo directly in the test file. I can't get the same behavior by setting a `location` header that contains a half of a pile of poo (`\uD83D`), because it seems somewhere that invalid character is being replace with an `=` sign.
I'm going to keep working at this, but it looks like it will take me longer than I expected.

**Comment by simov** [comment]
No problem, I'm kind of lost too, I though the error is about something else. Will take a look at it tomorrow.

**Comment by simov** [comment]
That line seems to be found in [node v10](https://github.com/nodejs/node/blob/2f947e966588d46f85a49e387b8b107e575dff1d/lib/url.js#L185) and it's about basic auth string encoded in the url, but I'm not able to reproduce the bug using url.parse.

**Comment by rifflock** [comment]
I'm not even entirely convinced that the `try-catch` around `url.parse` is the issue. Where I hit this issue in my code shouldn't be using any redirect logic. I just thought maybe I'd get lucky and this change would fix my issue.

I'm going to put `try-catch` blocks around my request calls in my code and see if it turns up anything. The error was pretty infrequent, maybe 15 times in 23000 calls. If I can get a more useful stack trace that points to something I'll open up a new pull request _with_ a functional test.

**Comment by simov** [comment]
:+1: thanks @rifflock

**Pull request closed without merging**
