### PR TITLE
Add tests and docs for using the agent, agentClass and agentOptions. Forever option defaults to using http(s).Agent in node 0.12+

### PR DESCRIPTION
**Pull request by simov**
Fixes https://github.com/request/request/issues/1637
Fixes https://github.com/request/request/issues/1669

Feedback: @mikeal @devTristan @triccardi-systran and anyone else interested in

- Take a look at the agent tests [here](https://github.com/simov/request/blob/agent-docs/tests/test-agent.js). Just a bunch of simple use cases, also note that the `forever` option defaults to `http(s).Agent` in node 0.12+
- Take a look at the [docs](https://github.com/simov/request/tree/agent-docs#requestoptions-callback) as well. A little bit down below there is a section for `agent` related options. It would be great if you read through all of them carefully and let me know if I'm not getting something right.

### CODE REVIEW

**Comment by simov** [comment]
@mikeal @devTristan @triccardi-systran (+ anyone else) any feedback on this one?

**Comment by devTristan** [comment]
I don't love `forever` being 0.10 only, as the docs say, but the code clearly supports the option in more recent versions. Why not get rid of the `console.warn` and keep `forever` as an option available for all versions?

**Comment by simov** [comment]
Probably a more appropriate way to document the `forever` option would be to say that it defaults to `http.Agent` in node 0.12+ which was suggested by @mikeal, also that's the way to get rid of potential bugs such as the memory leak one in your issue here https://github.com/request/request/issues/1637. The `console.warn` can be removed in that case I agree.

**Comment by simov** [comment]
@devTristan updated the [docs](https://github.com/simov/request/tree/agent-docs#requestoptions-callback) and removed the warning.

**Pull request merged**
