### PR TITLE
When adding realm to the front of the params array do not replace any…

### PR DESCRIPTION
**Pull request by jhalickman**
…thing in the array.

When using oauth with a realm I was losing one of the parameters we needed, changing 1 to 0 adds realm at the front with out removing anything from the array.

### CODE REVIEW

**Comment by simov** [comment]
Right that definitely looks like a bug. I'll fix the tests tomorrow :+1:

**Comment by jhalickman** [comment]
Awesome thanks

**Comment by simov** [comment]
@jhalickman can you pull https://github.com/simov/request/tree/oauth-realm-fix here? Then I'll merge it.

**Comment by jhalickman** [comment]
Sorry I am confused, what do you want me to do?

-- 
Joshua Halickman


On July 17, 2015 at 10:52:03 AM, simo (notifications@github.com) wrote:

@jhalickman can you pull https://github.com/simov/request/tree/oauth-realm-fix here? Then I'll merge it.

**Comment by simov** [comment]
Just `git pull git@github.com:simov/request.git oauth-realm-fix` into yours, and push again. If you have any difficulties I can figure out something on my end. You can apply the test fixes on your own too, we just need the tests passing here, in this PR, for the sake of completeness.

**Comment by jhalickman** [comment]
It looks like https://github.com/simov/request/commits/oauth-realm-fix already has my change in there, would I need to make any other changes?

-- 
Joshua Halickman


On July 17, 2015 at 11:31:46 AM, simo (notifications@github.com) wrote:

Just git pull git@github.com:simov/request.git oauth-realm-fix into yours, and push again. If you have any difficulties I can figure out something on my end. You can apply the test fixes on your own too, we just need the tests passing here, in this PR, for the sake of completeness.

**Comment by simov** [comment]
No, just execute the above command and push again, that's all.

**Comment by jhalickman** [comment]
Ahh I get it so you merge from my PR. Should be done.

-- 
Joshua Halickman


On July 17, 2015 at 11:49:22 AM, simo (notifications@github.com) wrote:

No, just execute the above command and push again, that's all.

**Comment by simov** [comment]
Yep I `fetch`'ed your branch and pushed to my repo.

Thanks :+1:

**Comment by jhalickman** [comment]
Just curious if this is going to get into NPM in the near future?

**Comment by simov** [comment]
I think we should have a new release pretty soon. Probably on Monday. I'm going to wrap up the latest PR's during the weekend and publish.

**Comment by jhalickman** [comment]
Awesome thanks for all the help!

-- 
Joshua Halickman


On July 17, 2015 at 12:06:26 PM, simo (notifications@github.com) wrote:

I think we should have a new release pretty soon. Probably on Monday. I'm going to wrap up the latest PR's during the weekend and publish.

**Comment by simov** [comment]
Version 2.59 is published https://github.com/request/request/issues/1683

**Pull request merged**
