### PR TITLE
Set certificate expiration to August 2, 2018

### PR DESCRIPTION
**Pull request by kevinburke**
Updates the gen-* scripts to take a `-days` argument, and set that `days`
argument to 3 years from now. I believe without this argument the certificates
default to a 30 day expiry. Code lifted from
https://github.com/shazow/urllib3/blob/master/dummyserver/certs/README.rst.

Generates new SSL certs with a long expiry.

### CODE REVIEW

**Comment by kevinburke** [comment]
whoops... need to check if this passes tests. 1 minute.

**Comment by simov** [comment]
Something isn't right with our tests lately, it's on my TODO list to investigate why they timeout so badly.

**Comment by kevinburke** [comment]
When I opened the PR the branches hung on `npm install` (not sure why). Triggered a rebuild and it looks like the tests are all passing.

**Comment by simov** [comment]
Thanks, now you can pull master :+1:

**Pull request merged**
