### PR TITLE
Honour RFC 1945 & RFC 2048

### PR DESCRIPTION
**Pull request by ThanosSiopoudis**
RFC 1945 & RFC 2048 state that upon a 301 or 302 redirect, user agents should not automatically change the request method to GET:

> Note: When automatically redirecting a POST request after
>        receiving a 301 status code, some existing user agents will
>        erroneously change it into a GET request.

(There is a relevant note for the 302 redirection as well)
https://tools.ietf.org/html/rfc1945#section-9.3

This relates to #2060

### CODE REVIEW

**Comment by FredKSchott** [comment]
Tests are failing, and this has gotten stale enough that merge conflicts need to be addressed.

>   If the 301 status code is received in response to a request using
>   the POST method, the user agent must not automatically redirect the
>   request unless it can be confirmed by the user, since this might
>   change the conditions under which the request was issued.

I agree that the current behavior is wrong, but redirecting as a POST is potentially worse. I would love to accept a PR to not redirect POSTs at all if you have the time.

**Comment by FredKSchott** [comment]
Thank you for including the spec btw, I wouldn't have been able to review this without it :)

**Comment by mikeal** [comment]
wait, are we actually changing the method to GET? I thought we *never* did that under the assumption that we needed to offer something lower level so that higher order libraries could customize how to interpret the spec?

**Comment by mikeal** [comment]
my memory may be failing me, or perhaps I just never noticed this land, but we should consider backing that out.

it's part of the spec but because of the layer we operate at we can't make assumptions about the intended behavior or our users when they are attempting to send a POST or PUT body. If that turns into a GET then their data isn't posted and we will be reporting a successful request with a 200 response which they will likely misinterpret.

**Comment by ThanosSiopoudis** [comment]
Exactly. Redirecting with a GET regardless of the requested method, does lead to misinterpretations. In reality, per the spec, it should either not follow the redirect and simply return it to the user to let him decide what to do with it, or add an option to either follow redirects with the original method, or not follow it at all.

If we can decide on how to approach this, I'm happy to clean this up and add any needed tests.

**Comment by FredKSchott** [comment]
@ThanosSiopoudis Can you rebase/merge the PR with master and see if this is still needed? A `followOriginalHttpMethod` option was added (possibly to address this) that isn't showing up in the PR diff.

**Comment by FredKSchott** [comment]
This PR has been closed as "abandoned" as a part of an automated cleanup. If this is a mistake and you are still interested in merging this PR, please do the following:

1. [ ] Rebase your changes onto the `master` branch (even if there are no merge conflicts, we want to make sure your change is under the most recent tests).
2. [ ] Push your updated branch to Github to update this PR.
3. [ ] Make sure this PR's Travis tests are still passing. (Run `npm test` locally if tests are still failing).
4. [ ] Comment here to let us know that you've updated the PR and are still interested in getting it merged. Somebody from the project will respond and work with you to review.

Thank you for your understanding. If you have any questions, please check out https://github.com/request/request/issues/2556 and feel free to comment / ask anything there.

**Pull request closed without merging**
