### PR TITLE
Request:Replaced PhantomJS with ChromeHeadless

### PR DESCRIPTION
**Pull request by ossdev07**
## PR Checklist:
- [x] I have run `npm test` locally and all tests are passing.

## PR Description
Phantomjs is an unmaintained project, removed phantomjs dependency from package.json and karma.conf.js. Added support for chrome headless to run the test suite.
Updated the start.js file to resolve the CORS policy issue in chrome headless.

### CODE REVIEW

**Comment by rhenwood-arm** [comment]
Is this patch ready to land? I would like to see PhantomJS removed because (not only is it unmaintained but) it doesn't have a AArch64 version available...

**Comment by ossdev07** [comment]
The travis-ci checks are failing on older NodeJS v8 and v6, in my view it should be dropped from the travis.yml and latest Nodejs versions should be added.

Please share your thoughts on this.

**Comment by ossdev07** [comment]
@andresroberto @mikeal @reconbot Please can someone have a look at this PR.

**Comment by ossdev07** [comment]
Ping @gr2m please could you have a look at this PR.

**Comment by gr2m** [comment]
Sorry @ossdev07, but request/request is deprecated, I won't be able to review any further PRs for it

**Pull request closed without merging**
