### PR TITLE
Updating tough-cookie due to security fix.

### PR DESCRIPTION
**Pull request by karlnorling**
## PR Checklist:
- [x] I have run `npm test` locally and all tests are passing.
- [x] I have added/updated tests for any new behavior.
       
- [x] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]
       

## PR Description
This addresses:
```
The tough-cookie module is vulnerable to regular expression denial of service. Input of around 50k characters is required for a slow down of around 2 seconds.

Unless node was compiled using the -DHTTPMAXHEADER_SIZE= option the default header max length is 80kb so the impact of the ReDoS is limited to around 7.3 seconds of blocking.

At the time of writing all version <=2.3.2 are vulnerable
```

- See: https://www.versioneye.com/Node.JS/tough-cookie/2.3.2
  - Also tough-cookie:
    - https://github.com/salesforce/tough-cookie/pull/97
    - https://github.com/salesforce/tough-cookie/pull/92

### CODE REVIEW

**Comment by mikeal** [comment]
Please don't update the version of request. The release script does that on its own :)

Other than that, it looks good.

**Comment by karlnorling** [comment]
@mikeal All done!

**Comment by austin-msi** [comment]
Any chance this can be merged today? I'd like to update my project ASAP 😃

**Comment by danihodovic** [comment]
Could this be merged soon to fix all the failing CI builds :smile:  ?

**Comment by avindra** [comment]
The security advisories have already been updated with the patched release of `tough-cookie`.

Can we please have a release of `request` cut with this fix?

**Comment by appility** [comment]
this merge is great but when I try to update with 
`npm install request@latest --save`
it only updates to 
"request": "^2.82.0"
which still refers to the older version of tough-cookie?

**Comment by Ilshidur** [comment]
@appility That is because latest **published** version is `2.82.0`. The GitHub repo currently has the `2.82.1` version already tagged but not yet published.
Unless I am mistaken, the changes made by this PR might be released in a new version : `2.82.2`.

**Pull request merged**
