### PR TITLE
Updated form-data to v2.0.0

### PR DESCRIPTION
**Pull request by alexindigo**
Re: https://twitter.com/mscdexdotexe/status/777025816635072512 + https://twitter.com/hichaelmart/status/776905912418263044

/cc @mscdex @simov

### CODE REVIEW

**Comment by alexindigo** [comment]
PS. On totally unrelated note, October 2016 is around the corner, do you think it's time to drop 0.10? :)

**Comment by mscdex** [comment]
Heh one step ahead of you (and one step behind greenkeeper bot): https://github.com/request/request/pull/2378 :-)

**Comment by alexindigo** [comment]
Haha :) it's nice to have something to choose from :)
Thank you btw for going all the way. :)

**Comment by simov** [comment]
@alexindigo we should probably drop support for anything below LTS at some point. I already excluded a few dependencies from greenkeeper because of ES* features used https://github.com/request/request/pull/2353/files

**Comment by simov** [comment]
LTS 4 I mean :)

**Comment by alexindigo** [comment]
I think 0.12 is used a lot in enterprise environments. Probably we can ask npm folks to publish stats on node versions talking to them.

And yes eslint+greenkeeper was most annoying thing :) So I created is-node-modern, so it'd run eslint only in newer node environments but I still can ci older versions. :)

I'll put back 0.10 support if you guys want to keep it after October. Right it now it works so it's just matter of travis-ci confing to prevent future breaks.

**Comment by alexindigo** [comment]
@simov Do you mind to publish new version to npm? Or you not sure if it's patch change?

**Comment by simov** [comment]
We use only _minor_ versions here, totally _not_ following semver. I'll remove 0.10 from TravisCI and I'll publish it.

**Comment by alexindigo** [comment]
I see. I just noticed `2.74.1` in the package.json and thought you already started publishing process. :)

Thank you.

**Comment by simov** [comment]
Done :sparkles: 

The version is **2.75.0**

**Comment by alexindigo** [comment]
Awesome thanks.

**Pull request closed without merging**
