### PR TITLE
Fixed calculation of oauth_body_hash, issue #2792

### PR DESCRIPTION
**Pull request by dvishniakov**
## PR Checklist:
- [x] I have run `npm test` locally and all tests are passing.
- [x] I have added/updated tests for any new behavior.
- If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]

## PR Description
FIxes https://github.com/request/request/issues/2792

### CODE REVIEW

**Comment by dvishniakov** [comment]
@mikeal any thoughts when this can be addressed?

**Comment by simov** [comment]
Thanks @dvishniakov :+1:

**Comment by aiham** [comment]
@simov Can we get the latest version published to NPM please?

**Comment by simov** [comment]
Sure, I've published 2.84.0 with the fix.

**Pull request merged**
