### PR TITLE
Allow piping data in next tick

### PR DESCRIPTION
**Pull request by aldeed**
This is a fix for https://github.com/mikeal/request/issues/887

### CODE REVIEW

**Comment by moll** [comment]
Just stumbled upon this problem as well, assuming the response object from `request(...).on("response")` would behave like one from `Http.get(...).on("response")`. Unfortunately because Request adds its own `data` listener to the response, the stream will be forced into flowing mode.

**Comment by nylen** [comment]
If we can get a PR for this that passes the old tests and the new ones (and a review from the original author) we'd take it.  I don't understand the issues well enough to do it myself.

Otherwise, we've got a good bit of work to do to move this code to streams2 and release a new major version.

Also... moll/vim-node#5 I still use this every day and would love to get support for it merged :)

**Comment by aldeed** [comment]
@raix, any chance you can figure out how to fix the three test failures caused by my change? See [my comment above](https://github.com/request/request/pull/1098#issuecomment-64133206)

**Comment by FredKSchott** [comment]
This PR has been closed as "abandoned" as a part of an automated cleanup. If this is a mistake and you are still interested in merging this PR, please do the following:

1. [ ] Rebase your changes onto the `master` branch (even if there are no merge conflicts, we want to make sure your change is under the most recent tests).
2. [ ] Push your updated branch to Github to update this PR.
3. [ ] Make sure this PR's Travis tests are still passing. (Run `npm test` locally if tests are still failing).
4. [ ] Comment here to let us know that you've updated the PR and are still interested in getting it merged. Somebody from the project will respond and work with you to review.

Thank you for your understanding. If you have any questions, please check out https://github.com/request/request/issues/2556 and feel free to comment / ask anything there.

**Pull request closed without merging**
