### PR TITLE
Catch errors from the underlying http module

### LINKED ISSUE #2120: request.get crashes with "The header content contains invalid characters"
Try this:

```
require('request').get('http://www.test.com/אבגד.pdf');
```

After a few milliseconds this crashes with `TypeError('The header content contains invalid characters')`

Now if I wrap it in `encodeUR` - it succeeds.
But if we receive urls from an external source - they may or may not be encoded. Is there some kind of built in mechanism to deal with this? (Other than doing `encodeURI(decodeURI(url))`)

### PR DESCRIPTION
**Pull request by simov**
Fixes #2120

### CODE REVIEW

**Comment by danielgindi** [comment]
:+1:

**Comment by Meabed** [comment]
👍

**Comment by khurrumqureshi** [comment]
👍

**Comment by simov** [comment]
Version 2.71 is published with the fix.

**Pull request merged**
