### PR TITLE
Allow static invoking of convenience methods

### PR DESCRIPTION
**Pull request by simov**
Fixes https://github.com/request/request/issues/1506

### CODE REVIEW

**Comment by kytwb** [comment]
Can we get a release for this asap?

**Comment by simov** [comment]
@kytwb we're rounding up a few more bugfixes and improvements, so until then you can use version 2.53 unless your code relies on features introduced in 2.54, in that case you can use the latest master in your package.json (not perfect)

```js
"request": "git://github.com/request/request.git"
```

**Comment by kytwb** [comment]
@simov: Most of our projects build is now broken due to this regression, would rather wait for a release if it's coming soon than changing the package.json in all the projects to finally rollback when the fix is out. Let me know.

**Comment by simov** [comment]
Ok, my assumption was that you have fixed dependency versions in your packages, which again my not be ideal but it's safer.

Anyway I understand that this bug is a problem for a lot of people, so it's better to have a new release soon. However there is one more bugfix submitted related to the same issue, then I'm going to make some improvements on that logic that caused the bugs. So we should wait a couple of days, probably till the end of the week.

**Comment by kytwb** [comment]
@simov: Fair enough, thanks for the prompt reply.

**Comment by simov** [comment]
2.55 is published on NPM

**Pull request merged**
