### PR TITLE
Fix issue #1038

### PR DESCRIPTION
**Pull request by guimonz**
I think this should fix the problem but I'm new to Node, so please forgive me if it's not good.

### CODE REVIEW

**Comment by guimonz** [comment]
cc @bmarini

**Comment by simov** [comment]
@guimonz that looks nice, can you add tests for this new behavior?

**Comment by guimonz** [comment]
Sure @simov!
I'll add them tonight! 
:-)

**Comment by simov** [comment]
Looking good, @guimonz can you pull https://github.com/simov/request/commit/bbcff4188629836662fb6e58c96cdf68f5876cc4 here? Only a minor indentation fixes, other than that :+1: from me.

**Comment by guimonz** [comment]
Here you go, @simov!

**Comment by simov** [comment]
Thanks @guimonz I'll merge this shortly.

**Comment by guimonz** [comment]
:+1:

**Comment by guimonz** [comment]
cc @bmarini

**Pull request merged**
