### PR TITLE
Update README.md with regards to Digest Auth

### PR DESCRIPTION
**Pull request by EivindArvesen**
Update README with details related to Digest authentication

## PR Checklist:
- [ ] I have run `npm test` locally and all tests are passing.
- [ ] I have added/updated tests for any new behavior.
       
- [ ] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]
       

## PR Description

Could only ever get Digest authentication to work by setting `withCredentials` to `true`.
Update README to reflect this.

### CODE REVIEW

**Comment by falcaosurfline** [comment]
This would be a really nice to have in AXIOS

**Comment by eivind88** [comment]
@mikeal What's the status on this?

**Comment by mikeal** [comment]
PR’s welcome for doc changes. `request` is in maintenance mode and won’t be taking new features, so any significant change in the code won’t happen.

**Comment by eivind88** [comment]
I see.
This PR only affects `README`, detailing how to make Digest authentication work

**Comment by EivindArvesen** [comment]
@mikeal What do you think? As I said, this PR only adds details to the README/docs on how to make Digest authentication work. The information already there isn't complete.

**Pull request closed without merging**
