### PR TITLE
Updated qs dependency to 5.2.0

### PR DESCRIPTION
**Pull request by acroca**
One of the things included in 5.2.0 is a `sort` option to stringify query strings sorted.

### CODE REVIEW

**Comment by chenchaoyi** [comment]
https://github.com/request/request/pull/1827

**Comment by simov** [comment]
I'm a bit confused, why was #1827 closed? @mikeal ?

**Comment by boennemann** [comment]
@simov Short version: Greenkeeper bug that's fixed now
Long version: https://github.com/greenkeeperio/support/issues/11#issuecomment-146476824

Either way: Sorry, our bad 😓

**Comment by simov** [comment]
:+1:

**Comment by acroca** [comment]
@mikeal When do you think you'll do the next release?

**Comment by mikeal** [comment]
if you want me to, today :)

**Comment by acroca** [comment]
:shipit:

**Comment by simov** [comment]
Can we wait a little bit? We have two more PRs that I want in the new release.

**Comment by acroca** [comment]
Sure, I'll be pointing to master in the meantime.

**Pull request merged**
