### PR TITLE
Deprecate Node v0.8.x

### LINKED ISSUE #1427: Deprecate 0.8 support
The policy so far has been to only support the last two stable versions of Node.

Deprecating 0.8 will make it easier for contributors to get the tests passing and make it much easier to move to new style streams.

### PR DESCRIPTION
**Pull request by nylen**
Closes #1427

### CODE REVIEW

**Comment by FredKSchott** [comment]
:+1: This would also mean we're no longer stuck with a super old version of eslint

**Comment by tikotzky** [comment]
:+1: but you should probably update the `engines` property in `package.json` to note that its not supported.

something like: ` "engines" : { "node" : ">=0.10 <0.12" }`

**Comment by rlidwka** [comment]
> something like: `"engines" : { "node" : ">=0.10 <0.12" }`

You'll cut off io.js this way.

**Comment by tikotzky** [comment]
@rlidwka right now iojs is not supported anyway, and  `engines` is just advisory so it wouldn't actually block you from installing and using on iojs.

**Comment by nylen** [comment]
@rlidwka ... can you propose a superior alternative?

**Comment by rlidwka** [comment]
> can you propose a superior alternative?

Maybe just use `{ "node": ">= 0.10" }`?

**Comment by nylen** [comment]
The problem with that is not everything works with `0.12` yet.  Let's discuss any changes to `engines` in a separate issue.

**Pull request merged**
