### PR TITLE
Recycle the agent when following a redirect

### PR DESCRIPTION
**Pull request by mattcg**
This fixes https://github.com/request/request/issues/1304. Passes all tests.

### CODE REVIEW

**Comment by nylen** [comment]
Any drawbacks to doing this?  Any thoughts on why it was done this way in the first place?

Can you think of an easy way to add a test for this behavior?

**Comment by mattcg** [comment]
I can't think of any drawbacks.

No idea why it was done in the first place. The message from the commit that added that line offers no explanation.

You mean an easy way to test whether the agent is reused?

**Comment by nylen** [comment]
> You mean an easy way to test whether the agent is reused?

yes.

**Comment by mattcg** [comment]
Closing pending discussion on #1304.

**Pull request closed without merging**
